import spotipy
import os
from spotipy.oauth2 import SpotifyOAuth

# Authenticate with Spotify API
sp = spotipy.Spotify(auth_manager=SpotifyOAuth(client_id='here',
                                               client_secret='and here',
                                               redirect_uri='https://its-codee.com',
                                               scope='playlist-modify-public'))
os.system('clear')
print(
    "░░░████████╗██╗░░██╗████████╗  ████████╗░█████╗░  ░██████╗██████╗░░█████╗░████████╗██╗███████╗██╗░░░██╗\n"
    "░░░╚══██╔══╝╚██╗██╔╝╚══██╔══╝  ╚══██╔══╝██╔══██╗  ██╔════╝██╔══██╗██╔══██╗╚══██╔══╝██║██╔════╝╚██╗░██╔╝\n"
    "░░░░░░██║░░░░╚███╔╝░░░░██║░░░  ░░░██║░░░██║░░██║  ╚█████╗░██████╔╝██║░░██║░░░██║░░░██║█████╗░░░╚████╔╝░\n"
    "░░░░░░██║░░░░██╔██╗░░░░██║░░░  ░░░██║░░░██║░░██║  ░╚═══██╗██╔═══╝░██║░░██║░░░██║░░░██║██╔══╝░░░░╚██╔╝░░\n"
    "██╗░░░██║░░░██╔╝╚██╗░░░██║░░░  ░░░██║░░░╚█████╔╝  ██████╔╝██║░░░░░╚█████╔╝░░░██║░░░██║██║░░░░░░░░██║░░░\n"
    "╚═╝░░░╚═╝░░░╚═╝░░╚═╝░░░╚═╝░░░  ░░░╚═╝░░░░╚════╝░  ╚═════╝░╚═╝░░░░░░╚════╝░░░░╚═╝░░░╚═╝╚═╝░░░░░░░░╚═╝░░░\n" 
)
print("This tool helps you to transform the text file generated by other applications (eg. spotify to text)\n"
      "into spotify playlists.\n")
play = input("Enter the playlist ID where you want to import the file (you find this in the playlist link. For example, the playlist ID for https://open.spotify.com/playlist/6nBPIX0KU3EoVLVylD5DKD it is 6nBPIX0KU3EoVLVylD5DKD): ")
filename = input("Enter filename (should be in same folder as this script): ")
# Load list of songs from file
with open(filename, 'r') as f:
    songs = f.readlines()

# Search for and add songs to the playlist
for song in songs:
    # Split the song name and artist name
    name, artist = song.strip().split(' - ')

    # Search for the song on Spotify
    results = sp.search(q=f'track:{name} artist:{artist}', type='track')

    # If a match is found, add the first result to the playlist
    if len(results['tracks']['items']) > 0:
        track = results['tracks']['items'][0]
        sp.user_playlist_add_tracks(user='also here',
                                     playlist_id=play,
                                     tracks=[track['uri']])
        print(f'Added "{track["name"]}" by {track["artists"][0]["name"]} to playlist.')
    
print("Songs imported.")

